/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TUGASVIRA;

import tugas6.*;
import tugas5.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author User
 */
public class elektronik1 extends javax.swing.JFrame {

    /**
     * Creates new form hp1
     */
    public elektronik1() {
        initComponents();
        DefaultTableModel dataModel = (DefaultTableModel) tabelhp.getModel();
        int rowCount = dataModel.getRowCount();
        while (rowCount > 0) {
            dataModel.removeRow(rowCount - 1);
            rowCount = dataModel.getRowCount(); // Update rowCount after removal
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtwarna = new javax.swing.JTextField();
        txtjumblah = new javax.swing.JTextField();
        txtharga = new javax.swing.JTextField();
        cmbjenis = new javax.swing.JComboBox<>();
        btninput = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtkodehp = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelhp = new javax.swing.JTable();
        btnclose = new javax.swing.JButton();
        cmbnama = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("rental HP Nila");

        jLabel2.setText("Jenis Elektronik :");

        jLabel3.setText("warna :");

        jLabel4.setText("Metode pembayaran :");

        jLabel5.setText("Jumblah :");

        jLabel6.setText("Harga :");

        btninput.setText("input data");
        btninput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninputActionPerformed(evt);
            }
        });

        jLabel7.setText("kode barang");

        tabelhp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Jenis elektronik", "Warna", "metode Pembayaran", "Kode elektronik", "Jumblah", "Harga", "Total harga"
            }
        ));
        jScrollPane3.setViewportView(tabelhp);

        btnclose.setText("close");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        cmbnama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "printer", "laptop", "musicbox", " " }));
        cmbnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbnamaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(277, 277, 277)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtwarna)
                                    .addComponent(cmbjenis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbnama, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(81, 81, 81)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtkodehp, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(txtharga)
                                    .addComponent(txtjumblah))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btninput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnclose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 370, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cmbnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtjumblah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(btninput))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtwarna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnclose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbjenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtkodehp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(89, 89, 89)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btninputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninputActionPerformed
        // TODO add your handling code here:
         
         String handphone="";
        if (cmbnama.getSelectedIndex()==0){
           laptop l = new laptop();
            l.datametode((String)cmbjenis.getSelectedItem());
            l.datawarna(txtwarna.getText());
            l.datajenis((String)cmbnama.getSelectedItem());
            l.datakode(txtkodehp.getText());
            l.datajumblah(Integer.parseInt(txtjumblah.getText()));
            l.dataharga(Integer.parseInt(txtharga.getText()));
            
            
            laptop harga = new laptop();
            harga.dataharga(Integer.parseInt(txtharga.getText()));
            harga.datajumblah(Integer.parseInt(txtjumblah.getText()));
            JOptionPane.showMessageDialog(this,l.input(l.jenis) );
            tabelhp.setAutoCreateColumnsFromModel(true);
        DefaultTableModel dataModel = (DefaultTableModel) tabelhp.getModel();
        List list = new ArrayList<>();
        list.add(l.jenis);
        list.add(l.warna);
        list.add(l.metode);
        list.add(l.kode_barang);
        list.add(l.jumblah);
        list.add(l.harga);
        list.add(l.totalelektronik());
        dataModel.addRow(list.toArray());
        } else if (cmbnama.getSelectedIndex()==1){
            printer p = new printer();
            p.datametode((String)cmbjenis.getSelectedItem());
            p.datawarna(txtwarna.getText());
            p.datajenis((String)cmbnama.getSelectedItem());
            p.datakode(txtkodehp.getText());
            p.datajumblah(Integer.parseInt(txtjumblah.getText()));
            p.dataharga(Integer.parseInt(txtharga.getText()));
            
            printer harga = new printer();
            harga.dataharga(Integer.parseInt(txtharga.getText()));
            harga.datajumblah(Integer.parseInt(txtjumblah.getText()));
            JOptionPane.showMessageDialog(this,p.input(p.jenis) );
             tabelhp.setAutoCreateColumnsFromModel(true);
        DefaultTableModel dataModel = (DefaultTableModel) tabelhp.getModel();
        List list = new ArrayList<>();
        list.add(p.jenis);
        list.add(p.warna);
        list.add(p.metode);
        list.add(p.kode_barang);
        list.add(p.jumblah);
        list.add(p.harga);
        list.add(p.totalelektronik());
        
        dataModel.addRow(list.toArray());
        } else if (cmbnama.getSelectedIndex()==2){
            musicbox m = new musicbox();
            m.datametode((String)cmbjenis.getSelectedItem());
            m.datawarna(txtwarna.getText());
            m.datajenis((String)cmbnama.getSelectedItem());
            m.datakode(txtkodehp.getText());
            m.datajumblah(Integer.parseInt(txtjumblah.getText()));
            m.dataharga(Integer.parseInt(txtharga.getText()));
          
            musicbox harga = new musicbox();
            harga.dataharga(Integer.parseInt(txtharga.getText()));
            harga.datajumblah(Integer.parseInt(txtjumblah.getText()));
            JOptionPane.showMessageDialog(this,m.input(m.jenis) );
             DefaultTableModel dataModel = (DefaultTableModel) tabelhp.getModel();
        List list = new ArrayList<>();
        list.add(m.jenis);
        list.add(m.warna);
        list.add(m.metode);
        list.add(m.kode_barang);
        list.add(m.jumblah);
        list.add(m.harga);
        list.add(m.totalelektronik());
        dataModel.addRow(list.toArray());
        }           
    }//GEN-LAST:event_btninputActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    private void cmbnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbnamaActionPerformed
   if(cmbnama.getSelectedIndex()==0){
           laptop l = new laptop();
           txtkodehp.setText(l.kode_barang());
            cmbjenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cardles","cash" }));
        } else if (cmbnama.getSelectedIndex()==1){
             printer p = new printer();
           txtkodehp.setText(p.kode_barang());
            cmbjenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cardles","cash" }));
        } else if (cmbnama.getSelectedIndex()==2){
           musicbox m = new musicbox();
           txtkodehp.setText(m.kode_barang());
            cmbjenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cardles","cash"}));
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cmbnamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(elektronik1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(elektronik1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(elektronik1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(elektronik1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new elektronik1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btninput;
    private javax.swing.JComboBox<String> cmbjenis;
    private javax.swing.JComboBox<String> cmbnama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabelhp;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtjumblah;
    private javax.swing.JTextField txtkodehp;
    private javax.swing.JTextField txtwarna;
    // End of variables declaration//GEN-END:variables
}
