/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas5;

/**
 *
 * @author User
 */
public class hp1 extends javax.swing.JFrame {

    /**
     * Creates new form hp1
     */
    public hp1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cmbnama = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtwarna = new javax.swing.JTextField();
        txtjumblah = new javax.swing.JTextField();
        txtharga = new javax.swing.JTextField();
        cmbjenis = new javax.swing.JComboBox<>();
        btninput = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        memohp = new javax.swing.JTextArea();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("rental HP Nila");

        cmbnama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Iphone", "Vivo", "Samsung", " " }));
        cmbnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbnamaActionPerformed(evt);
            }
        });

        jLabel2.setText("Jenis HP :");

        jLabel3.setText("warna");

        jLabel4.setText("Tipe :");

        jLabel5.setText("Jumblah :");

        jLabel6.setText("Harga :");

        btninput.setText("input data");
        btninput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninputActionPerformed(evt);
            }
        });

        memohp.setColumns(20);
        memohp.setRows(5);
        jScrollPane1.setViewportView(memohp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(18, 18, 18))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(45, 45, 45)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(50, 50, 50)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbnama, 0, 131, Short.MAX_VALUE)
                                    .addComponent(txtwarna)
                                    .addComponent(cmbjenis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtjumblah)
                                            .addComponent(txtharga, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)))
                                    .addComponent(btninput))))))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(cmbnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtjumblah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(txtwarna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbjenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btninput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbnamaActionPerformed
        // TODO add your handling code here:
        if(cmbnama.getSelectedIndex()==0){
            cmbjenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Iphone x", "Iphone XR","Iphone 11" }));
        } else if (cmbnama.getSelectedIndex()==1){
            cmbjenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "vivo y21", "vivo32","vivo 22x" }));
        } else if (cmbnama.getSelectedIndex()==2){
            cmbjenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Samsung s22", "Samsung s23","Samsung s11" }));
        }

    }//GEN-LAST:event_cmbnamaActionPerformed

    private void btninputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninputActionPerformed
        // TODO add your handling code here:
        memohp.setText("");
        if (cmbnama.getSelectedIndex()==0){
            iphone P = new iphone();
            P.datatipe((String)cmbjenis.getSelectedItem());
            P.datawarna(txtwarna.getText());
            P.datajenis((String)cmbnama.getSelectedItem());
            P.datajumblah(Integer.parseInt(txtjumblah.getText()));
            P.dataharga(Integer.parseInt(txtharga.getText()));
            
            memohp.append("Rental HP NILA\n");
            memohp.append("====================================================\n");
            memohp.append("Jenis HP\t: "+ P.cetakjenis()+"\n");            
            memohp.append("warna HP\t: "+ P.cetakwarna()+"\n");
            memohp.append("Tipe HP\t: "+ P.cetaktipe()+"\n");            
            memohp.append("Jumblah HP\t: "+ "Rp."+P.cetakjumblah()+"\n");
            memohp.append("Stok\t: "+ P.cetakharga()+"\n");
            iphone harga = new iphone();
            harga.dataharga(Integer.parseInt(txtharga.getText()));
            harga.datajumblah(Integer.parseInt(txtjumblah.getText()));
            memohp.append("Harga Total\t: "+harga.totalhp()+"\n");        
            memohp.append("====================================================\n");
            memohp.append(P.input(P.jenis));
        } else if (cmbnama.getSelectedIndex()==1){
            samsung s = new samsung();
            s.datatipe((String)cmbjenis.getSelectedItem());
            s.datawarna(txtwarna.getText());
            s.datajenis((String)cmbnama.getSelectedItem());
            s.datajumblah(Integer.parseInt(txtjumblah.getText()));
            s.dataharga(Integer.parseInt(txtharga.getText()));
            memohp.append("Rental HP NILA\n");
            memohp.append("====================================================\n");
            memohp.append("Jenis HP\t: "+ s.cetakjenis()+"\n");            
            memohp.append("warna HP\t: "+ s.cetakwarna()+"\n");
            memohp.append("Tipe HP\t: "+ s.cetaktipe()+"\n");            
            memohp.append("Jumblah HP\t: "+s.cetakjumblah()+"\n");
            memohp.append("Stok\t: "+ s.cetakharga()+"\n");
            samsung harga = new samsung();
            harga.dataharga(Integer.parseInt(txtharga.getText()));
            harga.datajumblah(Integer.parseInt(txtjumblah.getText()));
            memohp.append("Harga Total\t: "+ "Rp."+harga.totalhp()+"\n");        
            memohp.append("====================================================\n");
            memohp.append(s.input(s.jenis));
        } else if (cmbnama.getSelectedIndex()==2){
            vivo v = new vivo();
            v.datatipe((String)cmbjenis.getSelectedItem());
            v.datawarna(txtwarna.getText());
            v.datajenis((String)cmbnama.getSelectedItem());
            v.datajumblah(Integer.parseInt(txtjumblah.getText()));
            v.dataharga(Integer.parseInt(txtharga.getText()));
            memohp.append("Rental HP NILA\n");
            memohp.append("====================================================\n");
            memohp.append("Jenis HP\t: "+ v.cetakjenis()+"\n");            
            memohp.append("warna HP\t: "+ v.cetakwarna()+"\n");
            memohp.append("Tipe HP\t: "+ v.cetaktipe()+"\n");            
            memohp.append("Jumblah HP\t: "+ "Rp."+v.cetakjumblah()+"\n");
            memohp.append("Stok\t: "+ v.cetakharga()+"\n");
            vivo harga = new vivo();
            harga.dataharga(Integer.parseInt(txtharga.getText()));
            harga.datajumblah(Integer.parseInt(txtjumblah.getText()));
            memohp.append("Harga Total\t: "+harga.totalhp()+"\n");        
            memohp.append("====================================================\n");
            memohp.append(v.input(v.jenis));
        }           
    }//GEN-LAST:event_btninputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hp1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btninput;
    private javax.swing.JComboBox<String> cmbjenis;
    private javax.swing.JComboBox<String> cmbnama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea memohp;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtjumblah;
    private javax.swing.JTextField txtwarna;
    // End of variables declaration//GEN-END:variables
}
